// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `DJSCaseMgtConnection`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Server=DIT-MSSQL01-DV;Database=JusticeServices;User Id=JusticeServicesAppId;Password=******;`
//     Include Views:          `True`

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DJSCaseMgtService.Models
{
    /// <summary>
    /// A class which represents the FamilyProfiles_Remove table.
    /// </summary>
	[Table("FamilyProfiles_Remove")]
	public partial class FamilyProfilesRemove
	{
		[Key]
		public virtual int FamilyProfileID { get; set; }
		public virtual int ClientID { get; set; }
		public virtual int FamilyMemberID { get; set; }
		public virtual int? RelationshipID { get; set; }
		public virtual bool? PrimaryContact { get; set; }
		public virtual ClientRelationship ClientRelationship { get; set; }
	}

    /// <summary>
    /// A class which represents the OfficeLocation table.
    /// </summary>
	[Table("OfficeLocation")]
	public partial class OfficeLocation
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual int? DepartmentID { get; set; }
		public virtual string Name { get; set; }
		public virtual bool Active { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime CreatedDate { get; set; }
		public virtual int UpdatedBy { get; set; }
		public virtual DateTime UpdatedDate { get; set; }
		public virtual Department Department { get; set; }
		public virtual IEnumerable<Login> Login { get; set; }
	}

    /// <summary>
    /// A class which represents the ReferralOffense table.
    /// </summary>
	[Table("ReferralOffense")]
	public partial class ReferralOffense
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual int SystemID { get; set; }
		public virtual int ReferralID { get; set; }
		public virtual int OffenseID { get; set; }
		public virtual bool Active { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime CreatedDate { get; set; }
		public virtual int UpdatedBy { get; set; }
		public virtual DateTime UpdatedDate { get; set; }
		public virtual System System { get; set; }
		public virtual Referral Referral { get; set; }
		public virtual Offense Offense { get; set; }
	}

    /// <summary>
    /// A class which represents the ServiceUnit table.
    /// </summary>
	[Table("ServiceUnit")]
	public partial class ServiceUnit
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual int SystemID { get; set; }
		public virtual int ReferralID { get; set; }
		public virtual string Year { get; set; }
		public virtual string Month { get; set; }
		public virtual int Units { get; set; }
		public virtual bool Active { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime CreatedDate { get; set; }
		public virtual int UpdatedBy { get; set; }
		public virtual DateTime UpdatedDate { get; set; }
		public virtual System System { get; set; }
		public virtual Referral Referral { get; set; }
	}

    /// <summary>
    /// A class which represents the ReferralWorkDetails table.
    /// </summary>
	[Table("ReferralWorkDetails")]
	public partial class ReferralWorkDetail
	{
		[Key]
		public virtual int WorkDetailID { get; set; }
		public virtual int ReferralID { get; set; }
		public virtual DateTime DateWorked { get; set; }
		public virtual DateTime TimeIn { get; set; }
		public virtual DateTime TimeOut { get; set; }
		public virtual decimal HoursWorked { get; set; }
		public virtual int WorkSiteID { get; set; }
		public virtual int WorkTypeID { get; set; }
		public virtual string Comments { get; set; }
		public virtual DateTime? DateUpdated { get; set; }
		public virtual int? UpdatedById { get; set; }
		public virtual string UpdatedByName { get; set; }
		public virtual DateTime DateAdded { get; set; }
		public virtual int AddedById { get; set; }
		public virtual string AddedByName { get; set; }
		public virtual Referral Referral { get; set; }
		public virtual WorkSite WorkSite { get; set; }
		public virtual WorkType WorkType { get; set; }
	}

    /// <summary>
    /// A class which represents the ServiceProgramCategory table.
    /// </summary>
	[Table("ServiceProgramCategory")]
	public partial class ServiceProgramCategory
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual int? SystemID { get; set; }
		public virtual int? ServiceProgramID { get; set; }
		public virtual int? ServiceCategoryID { get; set; }
		public virtual bool Active { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime CreatedDate { get; set; }
		public virtual int UpdatedBy { get; set; }
		public virtual DateTime UpdatedDate { get; set; }
		public virtual ServiceProgram ServiceProgram { get; set; }
		public virtual ServiceCategory ServiceCategory { get; set; }
	}

    /// <summary>
    /// A class which represents the XRefProfileUser table.
    /// </summary>
	[Table("XRefProfileUser")]
	public partial class XRefProfileUser
	{
		public virtual int UserID { get; set; }
		public virtual int ServiceProfileID { get; set; }
		[Key]
		public virtual int XRefProfileUserID { get; set; }
		public virtual User User { get; set; }
		public virtual ServiceProviderProfile ServiceProviderProfile { get; set; }
	}

    /// <summary>
    /// A class which represents the FamilyProfile table.
    /// </summary>
	[Table("FamilyProfile")]
	public partial class FamilyProfile
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual int PersonID { get; set; }
		public virtual int FamilyMemberID { get; set; }
		public virtual int RelationshipID { get; set; }
		public virtual bool? PrimaryContacFlag { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime CreatedDate { get; set; }
		public virtual int UpdatedBy { get; set; }
		public virtual DateTime UpdatedDate { get; set; }
        public virtual Person Person { get; set; }
		public virtual Relationship Relationship { get; set; }
	}

    /// <summary>
    /// A class which represents the System table.
    /// </summary>
	[Table("System")]
	public partial class System
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual string Name { get; set; }
		public virtual bool Active { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime CreatedDate { get; set; }
		public virtual int UpdatedBy { get; set; }
		public virtual DateTime UpdatedDate { get; set; }
		public virtual IEnumerable<ClientProfile> ClientProfile { get; set; }
		public virtual IEnumerable<Referral> Referral { get; set; }
		public virtual IEnumerable<ServiceProgram> ServiceProgram { get; set; }
		public virtual IEnumerable<ServiceCategory> ServiceCategory { get; set; }
		public virtual IEnumerable<ServiceProvider> ServiceProvider { get; set; }
		public virtual IEnumerable<Assessment> Assessment { get; set; }
		public virtual IEnumerable<ServiceRelease> ServiceRelease { get; set; }
		public virtual IEnumerable<LoginProfile> LoginProfile { get; set; }
		public virtual IEnumerable<AssessmentType> AssessmentType { get; set; }
		public virtual IEnumerable<AssessmentSubtype> AssessmentSubtype { get; set; }
		public virtual IEnumerable<Application> Application { get; set; }
		public virtual IEnumerable<ReferralOffense> ReferralOffense { get; set; }
		public virtual IEnumerable<ServiceLevel> ServiceLevel { get; set; }
		public virtual IEnumerable<ServiceUnit> ServiceUnit { get; set; }
		public virtual IEnumerable<ServiceOutcome> ServiceOutcome { get; set; }
	}

    /// <summary>
    /// A class which represents the ServiceProgram table.
    /// </summary>
	[Table("ServiceProgram")]
	public partial class ServiceProgram
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual int SystemID { get; set; }
		public virtual string Name { get; set; }
		public virtual int? ServiceComponentID { get; set; }
		public virtual int? ServiceCategoryID { get; set; }
		public virtual int? ServiceLevelID { get; set; }
		public virtual int? ServiceProviderID { get; set; }
		public virtual bool Active { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime CreatedDate { get; set; }
		public virtual int UpdatedBy { get; set; }
		public virtual DateTime UpdatedDate { get; set; }
		public virtual System System { get; set; }
		public virtual ServiceProvider ServiceProvider { get; set; }
		public virtual IEnumerable<Referral> Referral { get; set; }
		public virtual IEnumerable<ServiceProgramCategory> ServiceProgramCategory { get; set; }
	}

    /// <summary>
    /// A class which represents the ServiceOutcomes table.
    /// </summary>
	[Table("ServiceOutcomes")]
	public partial class ServiceOutcome
	{
		[Key]
		public virtual int OutcomeID { get; set; }
		public virtual string Description { get; set; }
		public virtual bool Active { get; set; }
		public virtual DateTime? DateUpdated { get; set; }
		public virtual int? UpdatedById { get; set; }
		public virtual string UpdatedByName { get; set; }
		public virtual DateTime DateAdded { get; set; }
		public virtual int AddedById { get; set; }
		public virtual string AddedByName { get; set; }
		public virtual IEnumerable<Referral> Referrals { get; set; }
	}

    /// <summary>
    /// A class which represents the WorkSites table.
    /// </summary>
	[Table("WorkSites")]
	public partial class WorkSite
	{
		[Key]
		public virtual int WorkSiteID { get; set; }
		public virtual string _WorkSite { get; set; }
		public virtual bool Active { get; set; }
		public virtual DateTime? DateUpdated { get; set; }
		public virtual int? UpdatedById { get; set; }
		public virtual string UpdatedByName { get; set; }
		public virtual DateTime DateAdded { get; set; }
		public virtual int AddedById { get; set; }
		public virtual string AddedByName { get; set; }
		public virtual IEnumerable<ReferralWorkDetail> ReferralWorkDetails { get; set; }
	}

    /// <summary>
    /// A class which represents the Agency table.
    /// </summary>
	[Table("Agency")]
	public partial class Agency
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual string Description { get; set; }
		public virtual bool Active { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime CreatedDate { get; set; }
		public virtual int UpdatedBy { get; set; }
		public virtual DateTime UpdatedDate { get; set; }
		public virtual IEnumerable<Department> Department { get; set; }
	}

    /// <summary>
    /// A class which represents the VAOffenseCodes table.
    /// </summary>
	[Table("VAOffenseCodes")]
	public partial class VAOffenseCode
	{
		[Key]
		public virtual int OffenseID { get; set; }
		public virtual string Code { get; set; }
		public virtual string DYFS { get; set; }
		public virtual string VCCCode { get; set; }
		public virtual string GeneralHeading { get; set; }
		public virtual string OffenseType { get; set; }
		public virtual string OffenseDesc { get; set; }
		public virtual string Statute { get; set; }
		public virtual bool? Active { get; set; }
		public virtual DateTime? DateUpdated { get; set; }
		public virtual int? UpdatedById { get; set; }
		public virtual string UpdatedByName { get; set; }
		public virtual DateTime DateAdded { get; set; }
		public virtual int AddedById { get; set; }
		public virtual string AddedByName { get; set; }
		public virtual IEnumerable<Referral> Referrals { get; set; }
	}

    /// <summary>
    /// A class which represents the WorkTypes table.
    /// </summary>
	[Table("WorkTypes")]
	public partial class WorkType
	{
		[Key]
		public virtual int WorkTypeID { get; set; }
		public virtual string _WorkType { get; set; }
		public virtual bool Active { get; set; }
		public virtual DateTime? DateUpdated { get; set; }
		public virtual int? UpdatedById { get; set; }
		public virtual string UpdatedByName { get; set; }
		public virtual DateTime DateAdded { get; set; }
		public virtual int AddedById { get; set; }
		public virtual string AddedByName { get; set; }
		public virtual IEnumerable<ReferralWorkDetail> ReferralWorkDetails { get; set; }
	}

    /// <summary>
    /// A class which represents the AddressType table.
    /// </summary>
	[Table("AddressType")]
	public partial class AddressType
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual string Name { get; set; }
		public virtual string Description { get; set; }
		public virtual bool Active { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime CreatedDate { get; set; }
		public virtual int UpdatedBy { get; set; }
		public virtual DateTime UpdatedDate { get; set; }
		public virtual IEnumerable<PersonAddress> PersonAddress { get; set; }
	}

    /// <summary>
    /// A class which represents the Relationship table.
    /// </summary>
	[Table("Relationship")]
	public partial class Relationship
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual string Name { get; set; }
		public virtual string Description { get; set; }
		public virtual bool Active { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime CreatedDate { get; set; }
		public virtual int UpdatedBy { get; set; }
		public virtual DateTime UpdatedDate { get; set; }
		public virtual IEnumerable<FamilyProfile> FamilyProfile { get; set; }
	}

    /// <summary>
    /// A class which represents the Courts table.
    /// </summary>
	[Table("Courts")]
	public partial class Court
	{
		[Key]
		public virtual int CourtID { get; set; }
		public virtual string _Court { get; set; }
		public virtual bool Active { get; set; }
		public virtual DateTime? DateUpdated { get; set; }
		public virtual int? UpdatedById { get; set; }
		public virtual string UpdatedByName { get; set; }
		public virtual DateTime DateAdded { get; set; }
		public virtual int AddedById { get; set; }
		public virtual string AddedByName { get; set; }
		public virtual IEnumerable<Referral> Referrals { get; set; }
	}

    /// <summary>
    /// A class which represents the JobTitle table.
    /// </summary>
	[Table("JobTitle")]
	public partial class JobTitle
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual bool Active { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime CreatedDate { get; set; }
		public virtual int UpdatedBy { get; set; }
		public virtual DateTime UpdatedDate { get; set; }
		public virtual IEnumerable<Login> Login { get; set; }
	}

    /// <summary>
    /// A class which represents the ServiceProviderCategory table.
    /// </summary>
	[Table("ServiceProviderCategory")]
	public partial class ServiceProviderCategory
	{
		[Key]
		public virtual int ServiceProviderCategoryID { get; set; }
		public virtual string CategoryDescription { get; set; }
		public virtual string UpdatedBy { get; set; }
		public virtual DateTime? UpdatedOn { get; set; }
		public virtual bool Active { get; set; }
		public virtual IEnumerable<XRefServiceProgramCategory> XRefServiceProgramCategory { get; set; }
	}

    /// <summary>
    /// A class which represents the Application table.
    /// </summary>
	[Table("Application")]
	public partial class Application
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual int SystemID { get; set; }
		public virtual string Name { get; set; }
		public virtual bool Active { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime CreatedDate { get; set; }
		public virtual int UpdatedBy { get; set; }
		public virtual DateTime UpdatedDate { get; set; }
		public virtual System System { get; set; }
		public virtual IEnumerable<LoginProfile> LoginProfile { get; set; }
	}

    /// <summary>
    /// A class which represents the FamilyMembers table.
    /// </summary>
	[Table("FamilyMembers")]
	public partial class FamilyMember
	{
		[Key]
		public virtual int FamilyMemberID { get; set; }
		public virtual string LName { get; set; }
		public virtual string FName { get; set; }
		public virtual string MName { get; set; }
		public virtual string SufName { get; set; }
		public virtual string AddrID { get; set; }
		public virtual string SSN { get; set; }
		public virtual DateTime? DOB { get; set; }
		public virtual string POB { get; set; }
		public virtual string EducLevelCD { get; set; }
		public virtual string CourtRecord { get; set; }
		public virtual string MaritalStatus { get; set; }
		public virtual int? JobStatusID { get; set; }
		public virtual string Employer { get; set; }
		public virtual string WorkPhone { get; set; }
		public virtual string HomePhone { get; set; }
		public virtual string OtherPhone { get; set; }
		public virtual string PhysicalHealth { get; set; }
		public virtual string MentalHealth { get; set; }
		public virtual string SubstanceAbuse { get; set; }
		public virtual int? XRefJuv { get; set; }
		public virtual string CreatedBy { get; set; }
		public virtual DateTime? CreatedDt { get; set; }
		public virtual string UpdtBy { get; set; }
		public virtual DateTime? UpdtDt { get; set; }
		public virtual string Comments { get; set; }
		public virtual string WorkPhoneExt { get; set; }
		public virtual string OtherPhoneExt { get; set; }
		public virtual string income { get; set; }
		public virtual string RPSHomePhone { get; set; }
		public virtual string RPSWorkPhone { get; set; }
		public virtual string RPSOtherPhone { get; set; }
		public virtual int? ClientID { get; set; }
	}

    /// <summary>
    /// A class which represents the ServiceCategory table.
    /// </summary>
	[Table("ServiceCategory")]
	public partial class ServiceCategory
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual int SystemID { get; set; }
		public virtual string Name { get; set; }
		public virtual string Description { get; set; }
		public virtual bool Active { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime CreatedDate { get; set; }
		public virtual int UpdatedBy { get; set; }
		public virtual DateTime UpdatedDate { get; set; }
		public virtual System System { get; set; }
		public virtual IEnumerable<ServiceProgramCategory> ServiceProgramCategory { get; set; }
	}

    /// <summary>
    /// A class which represents the LoginDomain table.
    /// </summary>
	[Table("LoginDomain")]
	public partial class LoginDomain
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual string Name { get; set; }
		public virtual bool Active { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime CreatedDate { get; set; }
		public virtual int UpdatedBy { get; set; }
		public virtual DateTime UpdatedDate { get; set; }
		public virtual IEnumerable<LoginProfile> LoginProfile { get; set; }
	}

    /// <summary>
    /// A class which represents the ServiceLevel table.
    /// </summary>
	[Table("ServiceLevel")]
	public partial class ServiceLevel
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual int SystemID { get; set; }
		public virtual string Name { get; set; }
		public virtual string Description { get; set; }
		public virtual bool Active { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime CreatedDate { get; set; }
		public virtual int UpdatedBy { get; set; }
		public virtual DateTime UpdatedDate { get; set; }
		public virtual System System { get; set; }
		public virtual IEnumerable<Referral> Referral { get; set; }
	}

    /// <summary>
    /// A class which represents the ServiceOutcome table.
    /// </summary>
	[Table("ServiceOutcome")]
	public partial class ServiceOutcome
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual int SystemID { get; set; }
		public virtual string Name { get; set; }
		public virtual string Description { get; set; }
		public virtual bool Active { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime CreatedDate { get; set; }
		public virtual int UpdatedBy { get; set; }
		public virtual DateTime UpdatedDate { get; set; }
		public virtual System System { get; set; }
		public virtual IEnumerable<Referral> Referral { get; set; }
	}

    /// <summary>
    /// A class which represents the ViewXRefUserProfile view.
    /// </summary>
	[Table("ViewXRefUserProfile")]
	public partial class ViewXRefUserProfile
	{
		public virtual int UserID { get; set; }
		public virtual string FirstName { get; set; }
		public virtual string LastName { get; set; }
		public virtual string MiddleName { get; set; }
		public virtual string UserLogin { get; set; }
		public virtual string UserPassword { get; set; }
		public virtual string Email { get; set; }
		public virtual string JobTitle { get; set; }
		public virtual string PhoneNumber { get; set; }
		public virtual string Department { get; set; }
		public virtual bool? Active { get; set; }
		public virtual string Agency { get; set; }
		public virtual string OfficeAddress { get; set; }
		public virtual string Access { get; set; }
		public virtual string UpdatedBy { get; set; }
		public virtual DateTime? UpdatedOn { get; set; }
		public virtual string CreatedBy { get; set; }
		public virtual DateTime? CreatedOn { get; set; }
		public virtual int? UserRoleID { get; set; }
		public virtual string UserRoleName { get; set; }
		public virtual string UserRoleDescription { get; set; }
		public virtual int ServiceProfileID { get; set; }
		public virtual string ServiceProfileName { get; set; }
	}

    /// <summary>
    /// A class which represents the ServiceProvider table.
    /// </summary>
	[Table("ServiceProvider")]
	public partial class ServiceProvider
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual int SystemID { get; set; }
		public virtual string Name { get; set; }
		public virtual string Description { get; set; }
		public virtual bool Active { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime CreatedDate { get; set; }
		public virtual int UpdatedBy { get; set; }
		public virtual DateTime UpdatedDate { get; set; }
		public virtual System System { get; set; }
		public virtual IEnumerable<ServiceProgram> ServiceProgram { get; set; }
	}

    /// <summary>
    /// A class which represents the Judges table.
    /// </summary>
	[Table("Judges")]
	public partial class Judge
	{
		[Key]
		public virtual int JudgeID { get; set; }
		public virtual string JudgeName { get; set; }
		public virtual bool Active { get; set; }
		public virtual DateTime? DateUpdated { get; set; }
		public virtual int? UpdatedById { get; set; }
		public virtual string UpdatedByName { get; set; }
		public virtual DateTime DateAdded { get; set; }
		public virtual int AddedById { get; set; }
		public virtual string AddedByName { get; set; }
		public virtual IEnumerable<Referral> Referrals { get; set; }
	}

    /// <summary>
    /// A class which represents the LoginRole table.
    /// </summary>
	[Table("LoginRole")]
	public partial class LoginRole
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual string Name { get; set; }
		public virtual string Description { get; set; }
		public virtual bool Active { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime CreatedDate { get; set; }
		public virtual int UpdatedBy { get; set; }
		public virtual DateTime UpdatedDate { get; set; }
		public virtual IEnumerable<LoginProfile> LoginProfile { get; set; }
	}

    /// <summary>
    /// A class which represents the JuvenileClientFamilyInfo table.
    /// </summary>
	[Table("JuvenileClientFamilyInfo")]
	public partial class JuvenileClientFamilyInfo
	{
		public virtual int JuvFamilyId { get; set; }
		public virtual int JuvenileId { get; set; }
		public virtual int? FamilyProfileId { get; set; }
		public virtual string RoleId { get; set; }
		public virtual string CreatedBy { get; set; }
		public virtual DateTime? CreatedDt { get; set; }
		public virtual string UpdtBy { get; set; }
		public virtual DateTime? UpdtDt { get; set; }
		public virtual bool? PrimaryContact { get; set; }
	}

    /// <summary>
    /// A class which represents the SupplementalJuvenileClientInfo table.
    /// </summary>
	[Table("SupplementalJuvenileClientInfo")]
	public partial class SupplementalJuvenileClientInfo
	{
		[Key]
		public virtual int ClientID { get; set; }
		public virtual string BVCS { get; set; }
		public virtual string Medicaid { get; set; }
		public virtual string Insurance { get; set; }
		public virtual int? SchoolID { get; set; }
		public virtual string EducLevelCD { get; set; }
		public virtual string SchoolYr { get; set; }
		public virtual string ExceptionEduc { get; set; }
		public virtual string DriversLicense { get; set; }
		public virtual string OtherAgencyContacts { get; set; }
		public virtual string CreatedBy { get; set; }
		public virtual DateTime? CreatedDt { get; set; }
		public virtual string UpdtBy { get; set; }
		public virtual DateTime? UpdtDt { get; set; }
		public virtual string HobbiesInterests { get; set; }
		public virtual string DocketNumber { get; set; }
		public virtual string PhysicalHealth { get; set; }
		public virtual string MentalHealth { get; set; }
		public virtual string RPSHomePhone { get; set; }
		public virtual Client Client { get; set; }
		public virtual ClientSchool ClientSchool { get; set; }
	}

    /// <summary>
    /// A class which represents the ServiceProviderProgram table.
    /// </summary>
	[Table("ServiceProviderProgram")]
	public partial class ServiceProviderProgram
	{
		[Key]
		public virtual int ServiceProgramID { get; set; }
		public virtual int? ServiceProfileID { get; set; }
		public virtual string ServiceProgramName { get; set; }
		public virtual string ServiceProgramShortDescription { get; set; }
		public virtual string ServiceProgramDescription { get; set; }
		public virtual bool Active { get; set; }
		public virtual string UpdatedBy { get; set; }
		public virtual DateTime? UpdatedOn { get; set; }
		public virtual DateTime? InternalUpdatedOn { get; set; }
		public virtual string InternalUpdatedBy { get; set; }
		public virtual int? CurrentEnrollment { get; set; }
		public virtual int? TotalCapacity { get; set; }
		public virtual int? CurrentWaitlist { get; set; }
		public virtual int? SpaceAvailable { get; set; }
		public virtual string ProgramSpecificFor { get; set; }
		public virtual string ProgramCost { get; set; }
		public virtual string EvaluationCost { get; set; }
		public virtual string EvalCompleteConstraint { get; set; }
		public virtual bool? EvalCompleteConstraintSatisfied { get; set; }
		public virtual string NonEligiblePopulation { get; set; }
		public virtual string LengthOfProgram { get; set; }
		public virtual string FileName { get; set; }
		public virtual string MimeType { get; set; }
		public virtual byte[] FileObject { get; set; }
		public virtual int? TotalBytes { get; set; }
		public virtual DateTime? CurrentAsOfDate { get; set; }
		public virtual ServiceProviderProfile ServiceProviderProfile { get; set; }
		public virtual IEnumerable<Referral> Referrals { get; set; }
		public virtual IEnumerable<XrefProviderProgramComponent> XrefProviderProgramComponents { get; set; }
		public virtual IEnumerable<XRefServiceProgramCategory> XRefServiceProgramCategory { get; set; }
		public virtual IEnumerable<logServiceProgram> logServiceProgram { get; set; }
	}

    /// <summary>
    /// A class which represents the AssessmentType table.
    /// </summary>
	[Table("AssessmentType")]
	public partial class AssessmentType
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual int SystemID { get; set; }
		public virtual string Name { get; set; }
		public virtual string Description { get; set; }
		public virtual bool Active { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime CreatedDate { get; set; }
		public virtual int UpdatedBy { get; set; }
		public virtual DateTime UpdatedDate { get; set; }
		public virtual System System { get; set; }
		public virtual IEnumerable<Assessment> Assessment { get; set; }
	}

    /// <summary>
    /// A class which represents the Offense table.
    /// </summary>
	[Table("Offense")]
	public partial class Offense
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual string Name { get; set; }
		public virtual string DYFS { get; set; }
		public virtual string VCCCode { get; set; }
		public virtual string GeneralHeading { get; set; }
		public virtual string Type { get; set; }
		public virtual string Description { get; set; }
		public virtual string Statute { get; set; }
		public virtual bool Active { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime CreatedDate { get; set; }
		public virtual int UpdatedBy { get; set; }
		public virtual DateTime UpdatedDate { get; set; }
		public virtual IEnumerable<ReferralOffense> ReferralOffense { get; set; }
	}

    /// <summary>
    /// A class which represents the ClientSchools table.
    /// </summary>
	[Table("ClientSchools")]
	public partial class ClientSchool
	{
		[Key]
		public virtual int SchoolID { get; set; }
		public virtual string Phone { get; set; }
		public virtual string School { get; set; }
		public virtual string Principal { get; set; }
		public virtual string Address { get; set; }
		public virtual string Zip { get; set; }
		public virtual string Fax { get; set; }
		public virtual string EducationLevel { get; set; }
		public virtual string SchoolCode { get; set; }
		public virtual IEnumerable<SupplementalJuvenileClientInfo> SupplementalJuvenileClientInfo { get; set; }
	}

    /// <summary>
    /// A class which represents the AssessmentSubtype table.
    /// </summary>
	[Table("AssessmentSubtype")]
	public partial class AssessmentSubtype
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual int SystemID { get; set; }
		public virtual string Name { get; set; }
		public virtual string Description { get; set; }
		public virtual bool Active { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime CreatedDate { get; set; }
		public virtual int UpdatedBy { get; set; }
		public virtual DateTime UpdatedDate { get; set; }
		public virtual System System { get; set; }
		public virtual IEnumerable<Assessment> Assessment { get; set; }
	}

    /// <summary>
    /// A class which represents the Person table.
    /// </summary>
	[Table("Person")]
	public partial class Person
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual string LastName { get; set; }
		public virtual string FirstName { get; set; }
		public virtual string MiddleName { get; set; }
		public virtual string Suffix { get; set; }
		public virtual string JTS { get; set; }
		public virtual DateTime? DOB { get; set; }
		public virtual int? RaceID { get; set; }
		public virtual int? GenderID { get; set; }
		public virtual string SSN { get; set; }
		public virtual string DriversLicenseNumber { get; set; }
		public virtual bool Active { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime CreatedDate { get; set; }
		public virtual int UpdatedBy { get; set; }
		public virtual DateTime UpdatedDate { get; set; }
		public virtual Race Race { get; set; }
		public virtual Gender Gender { get; set; }
		public virtual IEnumerable<FamilyProfile> FamilyProfile { get; set; }
		public virtual IEnumerable<PersonSupplemental> PersonSupplemental { get; set; }
		public virtual IEnumerable<ClientProfile> ClientProfile { get; set; }
		public virtual IEnumerable<PersonAddress> PersonAddress { get; set; }
	}

    /// <summary>
    /// A class which represents the ClientAddresses table.
    /// </summary>
	[Table("ClientAddresses")]
	public partial class ClientAddress
	{
		[Key]
		public virtual int AddressId { get; set; }
		public virtual int? CORAddressId { get; set; }
		public virtual string BuildingNumber { get; set; }
		public virtual string BuildingSuffix { get; set; }
		public virtual string StreetDirection { get; set; }
		public virtual string StreetName { get; set; }
		public virtual string StreetNomenclature { get; set; }
		public virtual string UnitType { get; set; }
		public virtual string UnitNumber { get; set; }
		public virtual string City { get; set; }
		public virtual string State { get; set; }
		public virtual string ZipCode { get; set; }
		public virtual DateTime DateUpdated { get; set; }
		public virtual int UpdatedById { get; set; }
		public virtual string UpdatedByName { get; set; }
		public virtual DateTime DateAdded { get; set; }
		public virtual int AddedById { get; set; }
		public virtual string AddedByName { get; set; }
		public virtual IEnumerable<Client> Clients { get; set; }
	}

    /// <summary>
    /// A class which represents the ClientRelationship table.
    /// </summary>
	[Table("ClientRelationship")]
	public partial class ClientRelationship
	{
		[Key]
		public virtual int RelationshipID { get; set; }
		public virtual string RoleID { get; set; }
		public virtual string Relationship { get; set; }
		public virtual IEnumerable<FamilyProfilesRemove> FamilyProfilesRemove { get; set; }
	}

    /// <summary>
    /// A class which represents the vwClients_All view.
    /// </summary>
	[Table("vwClients_All")]
	public partial class vwClientsAll
	{
		public virtual int ClientID { get; set; }
		public virtual string SSN { get; set; }
		public virtual byte[] SSN_ENC { get; set; }
		public virtual long? SSN_Index { get; set; }
		public virtual string FirstName { get; set; }
		public virtual string LastName { get; set; }
		public virtual string MiddleName { get; set; }
		public virtual string NameSuffix { get; set; }
		public virtual DateTime DOB { get; set; }
		public virtual int RaceID { get; set; }
		public virtual int AddressId { get; set; }
		public virtual string JTS { get; set; }
		public virtual bool Active { get; set; }
		public virtual DateTime? DateUpdated { get; set; }
		public virtual int? UpdatedById { get; set; }
		public virtual string UpdatedByName { get; set; }
		public virtual DateTime DateAdded { get; set; }
		public virtual int AddedById { get; set; }
		public virtual string AddedByName { get; set; }
		public virtual int? Age { get; set; }
		public virtual int GenderID { get; set; }
		public virtual string Race { get; set; }
		public virtual string StateID { get; set; }
		public virtual string Gender { get; set; }
		public virtual string DriversLicenseNumber { get; set; }
		public virtual string HeightFt { get; set; }
		public virtual string HeightIn { get; set; }
		public virtual string Weight { get; set; }
		public virtual string HairColor { get; set; }
		public virtual string EyeColor { get; set; }
		public virtual string HomePhone { get; set; }
		public virtual string POB { get; set; }
	}

    /// <summary>
    /// A class which represents the SchoolLevel table.
    /// </summary>
	[Table("SchoolLevel")]
	public partial class SchoolLevel
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual string Name { get; set; }
		public virtual string Description { get; set; }
		public virtual bool Active { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime CreatedDate { get; set; }
		public virtual int UpdatedBy { get; set; }
		public virtual DateTime UpdatedDate { get; set; }
		public virtual IEnumerable<School> School { get; set; }
	}

    /// <summary>
    /// A class which represents the School table.
    /// </summary>
	[Table("School")]
	public partial class School
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual string Name { get; set; }
		public virtual string Phone { get; set; }
		public virtual string Principal { get; set; }
		public virtual string Address { get; set; }
		public virtual string Zip { get; set; }
		public virtual string Fax { get; set; }
		public virtual int SchoolLevelID { get; set; }
		public virtual int? SchoolCode { get; set; }
		public virtual bool Active { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime CreatedDate { get; set; }
		public virtual int UpdatedBy { get; set; }
		public virtual DateTime UpdatedDate { get; set; }
		public virtual SchoolLevel SchoolLevel { get; set; }
		public virtual IEnumerable<PersonSupplemental> PersonSupplemental { get; set; }
	}

    /// <summary>
    /// A class which represents the ViewXRefServiceProgramCategory view.
    /// </summary>
	[Table("ViewXRefServiceProgramCategory")]
	public partial class ViewXRefServiceProgramCategory
	{
		public virtual int XRefServiceProgramCategoryID { get; set; }
		public virtual int ServiceProviderCategoryID { get; set; }
		public virtual int ServiceProgramID { get; set; }
		public virtual int? ServiceProfileID { get; set; }
		public virtual string ServiceProgramName { get; set; }
		public virtual string ServiceProgramShortDescription { get; set; }
		public virtual string ServiceProgramDescription { get; set; }
		public virtual bool Active { get; set; }
		public virtual string UpdatedBy { get; set; }
		public virtual DateTime? UpdatedOn { get; set; }
		public virtual DateTime? InternalUpdatedOn { get; set; }
		public virtual string InternalUpdatedBy { get; set; }
		public virtual int? CurrentEnrollment { get; set; }
		public virtual int? TotalCapacity { get; set; }
		public virtual int? CurrentWaitlist { get; set; }
		public virtual string ProgramSpecificFor { get; set; }
		public virtual string ProgramCost { get; set; }
		public virtual string EvaluationCost { get; set; }
		public virtual string EvalCompleteConstraint { get; set; }
		public virtual bool? EvalCompleteConstraintSatisfied { get; set; }
		public virtual string NonEligiblePopulation { get; set; }
		public virtual string LengthOfProgram { get; set; }
		public virtual string FileName { get; set; }
		public virtual string MimeType { get; set; }
		public virtual byte[] FileObject { get; set; }
		public virtual int? TotalBytes { get; set; }
		public virtual string ServiceProfileName { get; set; }
	}

    /// <summary>
    /// A class which represents the ServiceRelease table.
    /// </summary>
	[Table("ServiceRelease")]
	public partial class ServiceRelease
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual int SystemID { get; set; }
		public virtual string Name { get; set; }
		public virtual bool ExcludeFromEnrollmentCount { get; set; }
		public virtual bool Active { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime CreatedDate { get; set; }
		public virtual int UpdatedBy { get; set; }
		public virtual DateTime UpdatedDate { get; set; }
		public virtual System System { get; set; }
		public virtual IEnumerable<Referral> Referral { get; set; }
	}

    /// <summary>
    /// A class which represents the Referrals table.
    /// </summary>
	[Table("Referrals")]
	public partial class Referral
	{
		[Key]
		public virtual int ReferralID { get; set; }
		public virtual int ClientID { get; set; }
		public virtual int OffenseID { get; set; }
		public virtual int ServiceProgramID { get; set; }
		public virtual decimal HoursAssigned { get; set; }
		public virtual decimal HoursCompleted { get; set; }
		public virtual int OutcomeID { get; set; }
		public virtual int JudgeID { get; set; }
		public virtual int CourtID { get; set; }
		public virtual DateTime DateOrdered { get; set; }
		public virtual DateTime DeadlineDate { get; set; }
		public virtual DateTime? ClientCheckInDate { get; set; }
		public virtual DateTime? ServiceBeginDate { get; set; }
		public virtual DateTime? ServiceEndDate { get; set; }
		public virtual DateTime? DateUpdated { get; set; }
		public virtual int? UpdatedById { get; set; }
		public virtual string UpdatedByName { get; set; }
		public virtual DateTime DateAdded { get; set; }
		public virtual int AddedById { get; set; }
		public virtual string AddedByName { get; set; }
		public virtual Client Client { get; set; }
		public virtual VAOffenseCode VAOffenseCode { get; set; }
		public virtual ServiceProviderProgram ServiceProviderProgram { get; set; }
		public virtual ServiceOutcome ServiceOutcome { get; set; }
		public virtual Judge Judge { get; set; }
		public virtual Court Court { get; set; }
		public virtual IEnumerable<ReferralWorkDetail> ReferralWorkDetails { get; set; }
	}

    /// <summary>
    /// A class which represents the Race table.
    /// </summary>
	[Table("Race")]
	public partial class Race
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual string Name { get; set; }
		public virtual string Description { get; set; }
		public virtual bool Active { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime CreatedDate { get; set; }
		public virtual int UpdatedBy { get; set; }
		public virtual DateTime UpdatedDate { get; set; }
		public virtual IEnumerable<Person> Person { get; set; }
	}

    /// <summary>
    /// A class which represents the vwClients_Juvenile view.
    /// </summary>
	[Table("vwClients_Juvenile")]
	public partial class vwClientsJuvenile
	{
		public virtual int ClientID { get; set; }
		public virtual string SSN { get; set; }
		public virtual long? SSN_Index { get; set; }
		public virtual string FirstName { get; set; }
		public virtual string LastName { get; set; }
		public virtual string MiddleName { get; set; }
		public virtual string NameSuffix { get; set; }
		public virtual DateTime DOB { get; set; }
		public virtual int RaceID { get; set; }
		public virtual int AddressId { get; set; }
		public virtual string JTS { get; set; }
		public virtual bool Active { get; set; }
		public virtual DateTime? DateUpdated { get; set; }
		public virtual int? UpdatedById { get; set; }
		public virtual string UpdatedByName { get; set; }
		public virtual DateTime DateAdded { get; set; }
		public virtual int AddedById { get; set; }
		public virtual string AddedByName { get; set; }
		public virtual int? Age { get; set; }
		public virtual int GenderID { get; set; }
		public virtual string Race { get; set; }
		public virtual string StateID { get; set; }
		public virtual string Gender { get; set; }
		public virtual string BVCS { get; set; }
		public virtual string Medicaid { get; set; }
		public virtual string Insurance { get; set; }
		public virtual int? SchoolID { get; set; }
		public virtual string EducLevelCD { get; set; }
		public virtual string SchoolYr { get; set; }
		public virtual string ExceptionEduc { get; set; }
		public virtual string DriversLicense { get; set; }
		public virtual string OtherAgencyContacts { get; set; }
		public virtual string CreatedBy { get; set; }
		public virtual DateTime? CreatedDt { get; set; }
		public virtual string UpdtBy { get; set; }
		public virtual DateTime? UpdtDt { get; set; }
		public virtual string HobbiesInterests { get; set; }
		public virtual string DocketNumber { get; set; }
		public virtual string PhysicalHealth { get; set; }
		public virtual string MentalHealth { get; set; }
		public virtual string RPSHomePhone { get; set; }
		public virtual string DriversLicenseNumber { get; set; }
		public virtual string HeightFt { get; set; }
		public virtual string HeightIn { get; set; }
		public virtual string Weight { get; set; }
		public virtual string HairColor { get; set; }
		public virtual string EyeColor { get; set; }
		public virtual string HomePhone { get; set; }
		public virtual string POB { get; set; }
	}

    /// <summary>
    /// A class which represents the LoginProfile table.
    /// </summary>
	[Table("LoginProfile")]
	public partial class LoginProfile
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual int SystemID { get; set; }
		public virtual int ApplicationID { get; set; }
		public virtual int LoginID { get; set; }
		public virtual int LoginRoleID { get; set; }
		public virtual int LoginDomainID { get; set; }
		public virtual string AccountName { get; set; }
		public virtual byte[] Password { get; set; }
		public virtual bool Active { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime CreatedDate { get; set; }
		public virtual int UpdatedBy { get; set; }
		public virtual DateTime UpdatedDate { get; set; }
		public virtual System System { get; set; }
		public virtual Application Application { get; set; }
		public virtual Login Login { get; set; }
		public virtual LoginRole LoginRole { get; set; }
		public virtual LoginDomain LoginDomain { get; set; }
	}

    /// <summary>
    /// A class which represents the vwClients_Adult view.
    /// </summary>
	[Table("vwClients_Adult")]
	public partial class vwClientsAdult
	{
		public virtual int ClientID { get; set; }
		public virtual string SSN { get; set; }
		public virtual long? SSN_Index { get; set; }
		public virtual string FirstName { get; set; }
		public virtual string LastName { get; set; }
		public virtual string MiddleName { get; set; }
		public virtual string NameSuffix { get; set; }
		public virtual DateTime DOB { get; set; }
		public virtual int RaceID { get; set; }
		public virtual int AddressId { get; set; }
		public virtual string JTS { get; set; }
		public virtual bool Active { get; set; }
		public virtual DateTime? DateUpdated { get; set; }
		public virtual int? UpdatedById { get; set; }
		public virtual string UpdatedByName { get; set; }
		public virtual DateTime DateAdded { get; set; }
		public virtual int AddedById { get; set; }
		public virtual string AddedByName { get; set; }
		public virtual int? Age { get; set; }
		public virtual int GenderID { get; set; }
		public virtual string Race { get; set; }
		public virtual string StateID { get; set; }
		public virtual string Gender { get; set; }
		public virtual string DriversLicenseNumber { get; set; }
		public virtual string HeightFt { get; set; }
		public virtual string HeightIn { get; set; }
		public virtual string Weight { get; set; }
		public virtual string HairColor { get; set; }
		public virtual string EyeColor { get; set; }
		public virtual string HomePhone { get; set; }
		public virtual string POB { get; set; }
	}

    /// <summary>
    /// A class which represents the vwStaff view.
    /// </summary>
	[Table("vwStaff")]
	public partial class vwStaff
	{
		public virtual int StaffID { get; set; }
		public virtual string Agency { get; set; }
		public virtual string LName { get; set; }
		public virtual string FName { get; set; }
		public virtual string NetLogin { get; set; }
		public virtual string Password { get; set; }
		public virtual string JobTitle { get; set; }
		public virtual string Phone { get; set; }
		public virtual string Fax { get; set; }
		public virtual string EMail { get; set; }
		public virtual string Department { get; set; }
		public virtual string OfficeLocation { get; set; }
		public virtual string NetworkConnection { get; set; }
		public virtual string AccessLevelReq { get; set; }
		public virtual string SQLRole { get; set; }
		public virtual DateTime? HireDt { get; set; }
		public virtual DateTime? TermDt { get; set; }
		public virtual bool? Active { get; set; }
		public virtual string RestrictLevel { get; set; }
		public virtual string Supervisor { get; set; }
		public virtual DateTime? AddDt { get; set; }
		public virtual string AddBy { get; set; }
		public virtual DateTime? UpdtDt { get; set; }
		public virtual string UpdtBy { get; set; }
	}

    /// <summary>
    /// A class which represents the XRefServiceProgramCategory table.
    /// </summary>
	[Table("XRefServiceProgramCategory")]
	public partial class XRefServiceProgramCategory
	{
		[Key]
		public virtual int XRefServiceProgramCategoryID { get; set; }
		public virtual int ServiceProviderCategoryID { get; set; }
		public virtual int ServiceProgramID { get; set; }
		public virtual ServiceProviderCategory ServiceProviderCategory { get; set; }
		public virtual ServiceProviderProgram ServiceProviderProgram { get; set; }
	}

    /// <summary>
    /// A class which represents the Judge table.
    /// </summary>
	[Table("Judge")]
	public partial class Judge
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual string Name { get; set; }
		public virtual bool Active { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime CreatedDate { get; set; }
		public virtual int UpdatedBy { get; set; }
		public virtual DateTime UpdatedDate { get; set; }
		public virtual IEnumerable<Referral> Referral { get; set; }
	}

    /// <summary>
    /// A class which represents the PersonSupplemental table.
    /// </summary>
	[Table("PersonSupplemental")]
	public partial class PersonSupplemental
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual int PersonID { get; set; }
		public virtual string DocketNumber { get; set; }
		public virtual string POB { get; set; }
		public virtual string CourtRecord { get; set; }
		public virtual string MaritalStatus { get; set; }
		public virtual int? JobStatusID { get; set; }
		public virtual string Employer { get; set; }
		public virtual string HomePhone { get; set; }
		public virtual string WorkPhone { get; set; }
		public virtual string OtherPhone { get; set; }
		public virtual string BVCS { get; set; }
		public virtual string HeightFt { get; set; }
		public virtual string HeightIn { get; set; }
		public virtual string Weight { get; set; }
		public virtual string HairColor { get; set; }
		public virtual string EyeColor { get; set; }
		public virtual string Medicaid { get; set; }
		public virtual string Insurance { get; set; }
		public virtual int? SchoolID { get; set; }
		public virtual int? EducID { get; set; }
		public virtual int? EducationLevelID { get; set; }
		public virtual string SchoolYr { get; set; }
		public virtual string ExceptionEduc { get; set; }
		public virtual string OtherAgencyContacts { get; set; }
		public virtual string PhysicalHealth { get; set; }
		public virtual string MentalHealth { get; set; }
		public virtual string SubstanceAbuse { get; set; }
		public virtual int? XRefJuv { get; set; }
		public virtual string Comments { get; set; }
		public virtual string WorkPhoneExt { get; set; }
		public virtual string OtherPhoneExt { get; set; }
		public virtual string income { get; set; }
		public virtual string RPSHomePhone { get; set; }
		public virtual string RPSWorkPhone { get; set; }
		public virtual string RPSOtherPhone { get; set; }
		public virtual string HobbiesInterests { get; set; }
		public virtual bool Active { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime CreatedDate { get; set; }
		public virtual int UpdatedBy { get; set; }
		public virtual DateTime UpdatedDate { get; set; }
		public virtual Person Person { get; set; }
		public virtual JobStatu JobStatu { get; set; }
		public virtual School School { get; set; }
		public virtual EducationLevel EducationLevel { get; set; }
	}

    /// <summary>
    /// A class which represents the logServiceProgram table.
    /// </summary>
	[Table("logServiceProgram")]
	public partial class logServiceProgram
	{
		[Key]
		public virtual int logServiceProgramID { get; set; }
		public virtual DateTime SystemDate { get; set; }
		public virtual int TotalCapacity { get; set; }
		public virtual int Enrollment { get; set; }
		public virtual int SpaceAvailable { get; set; }
		public virtual DateTime CurrentAsOfDate { get; set; }
		public virtual int ServiceProgramID { get; set; }
		public virtual string UpdatedBy { get; set; }
		public virtual string ServiceProgramName { get; set; }
		public virtual int CurrentWaitlist { get; set; }
		public virtual ServiceProviderProgram ServiceProviderProgram { get; set; }
	}

    /// <summary>
    /// A class which represents the ClientProfile table.
    /// </summary>
	[Table("ClientProfile")]
	public partial class ClientProfile
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual int SystemID { get; set; }
		public virtual int PersonID { get; set; }
		public virtual bool Active { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime CreatedDate { get; set; }
		public virtual int UpdatedBy { get; set; }
		public virtual DateTime UpdatedDate { get; set; }
		public virtual System System { get; set; }
		public virtual Person Person { get; set; }
		public virtual IEnumerable<Referral> Referral { get; set; }
		public virtual IEnumerable<Assessment> Assessment { get; set; }
	}

    /// <summary>
    /// A class which represents the ClientGender table.
    /// </summary>
	[Table("ClientGender")]
	public partial class ClientGender
	{
		[Key]
		public virtual int GenderID { get; set; }
		public virtual string Gender { get; set; }
		public virtual IEnumerable<Client> Clients { get; set; }
	}

    /// <summary>
    /// A class which represents the ServiceProviderProgramComponents table.
    /// </summary>
	[Table("ServiceProviderProgramComponents")]
	public partial class ServiceProviderProgramComponent
	{
		[Key]
		public virtual int ProgramComponentId { get; set; }
		public virtual string ProgramComponentName { get; set; }
		public virtual bool Active { get; set; }
		public virtual string UpdatedBy { get; set; }
		public virtual DateTime UpdatedOn { get; set; }
		public virtual IEnumerable<XrefProviderProgramComponent> XrefProviderProgramComponents { get; set; }
	}

    /// <summary>
    /// A class which represents the Department table.
    /// </summary>
	[Table("Department")]
	public partial class Department
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual int AgencyID { get; set; }
		public virtual string Name { get; set; }
		public virtual bool Active { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime CreatedDate { get; set; }
		public virtual int UpdatedBy { get; set; }
		public virtual DateTime UpdatedDate { get; set; }
		public virtual Agency Agency { get; set; }
		public virtual IEnumerable<OfficeLocation> OfficeLocation { get; set; }
	}

    /// <summary>
    /// A class which represents the Assessment table.
    /// </summary>
	[Table("Assessment")]
	public partial class Assessment
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual int SystemID { get; set; }
		public virtual int? ClientProfileID { get; set; }
		public virtual int? LoginProfileID { get; set; }
		public virtual string OffenseComments { get; set; }
		public virtual string FamilyComments { get; set; }
		public virtual string EducationComments { get; set; }
		public virtual string PeerComments { get; set; }
		public virtual string SubstanceComments { get; set; }
		public virtual string BehaviorComments { get; set; }
		public virtual string MentalComments { get; set; }
		public virtual string CurrentCharge { get; set; }
		public virtual string Placement { get; set; }
		public virtual string Service { get; set; }
		public virtual string SocialHistory { get; set; }
		public virtual string Level1Case_Div { get; set; }
		public virtual string Level2Case { get; set; }
		public virtual string CommentsStrength { get; set; }
		public virtual string Source { get; set; }
		public virtual DateTime? AssessmentDate { get; set; }
		public virtual int? AssessmentTypeID { get; set; }
		public virtual int? AssessmentSubtypeID { get; set; }
		public virtual string AssessmentScore { get; set; }
		public virtual string Notes { get; set; }
		public virtual bool Active { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime CreatedDate { get; set; }
		public virtual int UpdatedBy { get; set; }
		public virtual DateTime UpdatedDate { get; set; }
		public virtual System System { get; set; }
		public virtual ClientProfile ClientProfile { get; set; }
		public virtual AssessmentType AssessmentType { get; set; }
		public virtual AssessmentSubtype AssessmentSubtype { get; set; }
	}

    /// <summary>
    /// A class which represents the User table.
    /// </summary>
	[Table("User")]
	public partial class User
	{
		[Key]
		public virtual int UserID { get; set; }
		public virtual string FirstName { get; set; }
		public virtual string LastName { get; set; }
		public virtual string MiddleName { get; set; }
		public virtual string UserLogin { get; set; }
		public virtual string Email { get; set; }
		public virtual string JobTitle { get; set; }
		public virtual string PhoneNumber { get; set; }
		public virtual int? DepartmentID { get; set; }
		public virtual string Department { get; set; }
		public virtual bool? Active { get; set; }
		public virtual int? AgencyID { get; set; }
		public virtual string Agency { get; set; }
		public virtual string OfficeAddress { get; set; }
		public virtual string Access { get; set; }
		public virtual string UpdatedBy { get; set; }
		public virtual DateTime? UpdatedOn { get; set; }
		public virtual string CreatedBy { get; set; }
		public virtual DateTime? CreatedOn { get; set; }
		public virtual int UserRoleID { get; set; }
		public virtual byte[] UserPassword { get; set; }
		public virtual DateTime? LastLoggedIn { get; set; }
		public virtual UserRole UserRole { get; set; }
		public virtual IEnumerable<XRefProfileUser> XRefProfileUser { get; set; }
	}

    /// <summary>
    /// A class which represents the EducationLevel table.
    /// </summary>
	[Table("EducationLevel")]
	public partial class EducationLevel
	{
		public virtual int ID { get; set; }
		public virtual string Name { get; set; }
		public virtual bool Active { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime CreatedDate { get; set; }
		public virtual int UpdatedBy { get; set; }
		public virtual DateTime UpdatedDate { get; set; }
		public virtual IEnumerable<PersonSupplemental> PersonSupplemental { get; set; }
	}

    /// <summary>
    /// A class which represents the Login table.
    /// </summary>
	[Table("Login")]
	public partial class Login
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual string FirstName { get; set; }
		public virtual string LastName { get; set; }
		public virtual string MiddleName { get; set; }
		public virtual string Email { get; set; }
		public virtual int? JobTitleID { get; set; }
		public virtual string PhoneNumber { get; set; }
		public virtual string FaxNumber { get; set; }
		public virtual int? OfficeLocationID { get; set; }
		public virtual string tempAccountName { get; set; }
		public virtual string tempPassword { get; set; }
		public virtual int? tempStaffID { get; set; }
		public virtual string tempAccess { get; set; }
		public virtual string tempAgency { get; set; }
		public virtual string tempDepartment { get; set; }
		public virtual string tempOfficeLocation { get; set; }
		public virtual string tempNetworkConnection { get; set; }
		public virtual string tempSupervisor { get; set; }
		public virtual bool? Active { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime CreatedDate { get; set; }
		public virtual int UpdatedBy { get; set; }
		public virtual DateTime UpdatedDate { get; set; }
		public virtual DateTime? LastLoggedIn { get; set; }
		public virtual JobTitle JobTitle { get; set; }
		public virtual OfficeLocation OfficeLocation { get; set; }
		public virtual IEnumerable<LoginProfile> LoginProfile { get; set; }
	}

    /// <summary>
    /// A class which represents the XrefProviderProgramComponents table.
    /// </summary>
	[Table("XrefProviderProgramComponents")]
	public partial class XrefProviderProgramComponent
	{
		[Key]
		public virtual int xrefProviderProgramComponentsId { get; set; }
		public virtual int ServiceProgramId { get; set; }
		public virtual int ProgramComponentId { get; set; }
		public virtual ServiceProviderProgram ServiceProviderProgram { get; set; }
		public virtual ServiceProviderProgramComponent ServiceProviderProgramComponent { get; set; }
	}

    /// <summary>
    /// A class which represents the Gender table.
    /// </summary>
	[Table("Gender")]
	public partial class Gender
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual string Name { get; set; }
		public virtual bool Active { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime CreatedDate { get; set; }
		public virtual int UpdatedBy { get; set; }
		public virtual DateTime UpdatedDate { get; set; }
		public virtual IEnumerable<Person> Person { get; set; }
	}

    /// <summary>
    /// A class which represents the UserRole table.
    /// </summary>
	[Table("UserRole")]
	public partial class UserRole
	{
		[Key]
		public virtual int UserRoleID { get; set; }
		public virtual string UserRoleName { get; set; }
		public virtual string UserRoleDescription { get; set; }
		public virtual string UpdatedBy { get; set; }
		public virtual DateTime? UpdatedOn { get; set; }
		public virtual IEnumerable<User> User { get; set; }
	}

    /// <summary>
    /// A class which represents the JobStatus table.
    /// </summary>
	[Table("JobStatus")]
	public partial class JobStatu
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual string Name { get; set; }
		public virtual bool Active { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime CreatedDate { get; set; }
		public virtual int UpdatedBy { get; set; }
		public virtual DateTime UpdatedDate { get; set; }
		public virtual IEnumerable<PersonSupplemental> PersonSupplemental { get; set; }
	}

    /// <summary>
    /// A class which represents the sysdiagrams table.
    /// </summary>
	[Table("sysdiagrams")]
	public partial class sysdiagram
	{
		public virtual string name { get; set; }
		public virtual int principal_id { get; set; }
		[Key]
		public virtual int diagram_id { get; set; }
		public virtual int? version { get; set; }
		public virtual byte[] definition { get; set; }
	}

    /// <summary>
    /// A class which represents the ServiceProviderProfile table.
    /// </summary>
	[Table("ServiceProviderProfile")]
	public partial class ServiceProviderProfile
	{
		[Key]
		public virtual int ServiceProfileID { get; set; }
		public virtual string ServiceProfileName { get; set; }
		public virtual string ServiceProfileDescription { get; set; }
		public virtual bool Active { get; set; }
		public virtual string UpdatedBy { get; set; }
		public virtual DateTime? UpdatedOn { get; set; }
		public virtual IEnumerable<ServiceProviderProgram> ServiceProviderProgram { get; set; }
		public virtual IEnumerable<XRefProfileUser> XRefProfileUser { get; set; }
	}

    /// <summary>
    /// A class which represents the PersonAddress table.
    /// </summary>
	[Table("PersonAddress")]
	public partial class PersonAddress
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual int PersonID { get; set; }
		public virtual int AddressTypeID { get; set; }
		public virtual string GISCode { get; set; }
		public virtual double? Latitude { get; set; }
		public virtual double? Longitude { get; set; }
		public virtual string AptNo { get; set; }
		public virtual string POBox { get; set; }
		public virtual bool Active { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime CreatedDate { get; set; }
		public virtual int UpdatedBy { get; set; }
		public virtual DateTime UpdatedDate { get; set; }
		public virtual Person Person { get; set; }
		public virtual AddressType AddressType { get; set; }
	}

    /// <summary>
    /// A class which represents the Clients table.
    /// </summary>
	[Table("Clients")]
	public partial class Client
	{
		[Key]
		public virtual int ClientID { get; set; }
		public virtual byte[] SSN { get; set; }
		public virtual long? SSN_Index { get; set; }
		public virtual string DriversLicenseNumber { get; set; }
		public virtual string JTS { get; set; }
		public virtual string FirstName { get; set; }
		public virtual string LastName { get; set; }
		public virtual string MiddleName { get; set; }
		public virtual string NameSuffix { get; set; }
		public virtual DateTime DOB { get; set; }
		public virtual int GenderID { get; set; }
		public virtual int RaceID { get; set; }
		public virtual string HeightFt { get; set; }
		public virtual string HeightIn { get; set; }
		public virtual string Weight { get; set; }
		public virtual string HairColor { get; set; }
		public virtual string EyeColor { get; set; }
		public virtual int AddressId { get; set; }
		public virtual string HomePhone { get; set; }
		public virtual string POB { get; set; }
		public virtual bool Active { get; set; }
		public virtual DateTime? DateUpdated { get; set; }
		public virtual int? UpdatedById { get; set; }
		public virtual string UpdatedByName { get; set; }
		public virtual DateTime DateAdded { get; set; }
		public virtual int AddedById { get; set; }
		public virtual string AddedByName { get; set; }
		public virtual ClientGender ClientGender { get; set; }
		public virtual ClientRace ClientRace { get; set; }
		public virtual ClientAddress ClientAddress { get; set; }
		public virtual IEnumerable<Referral> Referrals { get; set; }
		public virtual IEnumerable<SupplementalJuvenileClientInfo> SupplementalJuvenileClientInfo { get; set; }
	}

    /// <summary>
    /// A class which represents the Referral table.
    /// </summary>
	[Table("Referral")]
	public partial class Referral
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual int SystemID { get; set; }
		public virtual int? ClientProfileID { get; set; }
		public virtual DateTime? AssessDate { get; set; }
		public virtual int? AssessScore { get; set; }
		public virtual DateTime? CourtOrderDate { get; set; }
		public virtual DateTime? NextCourtDate { get; set; }
		public virtual string CourtOrderNarrative { get; set; }
		public virtual int? PlacementLevelID { get; set; }
		public virtual int? ReferralSourceID { get; set; }
		public virtual string Service { get; set; }
		public virtual string PlacementCharges { get; set; }
		public virtual int? AgeAtTime { get; set; }
		public virtual int? JudgeID { get; set; }
		public virtual string ChargeComments { get; set; }
		public virtual int ServiceProgramID { get; set; }
		public virtual int? RefSourceID { get; set; }
		public virtual string BasisofReferral { get; set; }
		public virtual DateTime? SourceContactedDate { get; set; }
		public virtual DateTime? InitMeetingDate { get; set; }
		public virtual string Comments { get; set; }
		public virtual string SuppComments { get; set; }
		public virtual DateTime? BeginDt { get; set; }
		public virtual DateTime? EndDt { get; set; }
		public virtual string Outcome { get; set; }
		public virtual int? ServiceOutcomeID { get; set; }
		public virtual int? ServiceReleaseID { get; set; }
		public virtual DateTime? DateofReferral { get; set; }
		public virtual int? CounselorID { get; set; }
		public virtual string RefSourceNotes { get; set; }
		public virtual string MonitorOption { get; set; }
		public virtual int? ComHoursAssigned { get; set; }
		public virtual int? InterventionID { get; set; }
		public virtual int? LoginProfileID { get; set; }
		public virtual bool Active { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime CreatedDate { get; set; }
		public virtual int UpdatedBy { get; set; }
		public virtual DateTime UpdatedDate { get; set; }
		public virtual System System { get; set; }
		public virtual ClientProfile ClientProfile { get; set; }
		public virtual ServiceLevel ServiceLevel { get; set; }
		public virtual Judge Judge { get; set; }
		public virtual ServiceProgram ServiceProgram { get; set; }
		public virtual ServiceOutcome ServiceOutcome { get; set; }
		public virtual ServiceRelease ServiceRelease { get; set; }
		public virtual IEnumerable<ReferralOffense> ReferralOffense { get; set; }
		public virtual IEnumerable<ServiceUnit> ServiceUnit { get; set; }
	}

    /// <summary>
    /// A class which represents the ClientRace table.
    /// </summary>
	[Table("ClientRace")]
	public partial class ClientRace
	{
		[Key]
		public virtual int RaceID { get; set; }
		public virtual string Race { get; set; }
		public virtual string RaceCode { get; set; }
		public virtual string StateID { get; set; }
		public virtual IEnumerable<Client> Clients { get; set; }
	}

}
